### ISSUE TITLE
Add functionality to retrieve and change Physics Settings

### ISSUE THREAD

**Issue by Remasuri** [DenchiSoft/VTubeStudio#15]
Would be great if we could work with the Physics Settings to create some interesting tools! (Hotkey functionality would also be great). I noticed that some streamers like to set their physics to maximum for redeems, so I think this feature would see some use! 

I could also imagine that people could craft custom Overlays with leaves blowing through the screen in the direction of the "wind" parameter.

**Comment by DenchiSoft** [comment]
Thanks for the suggestion. There will be functionality to set wind and physics strength on a per-parameter basis. After that is implemented, it will be exposed on the API as well.

I'll leave this open until then.

**Comment by DenchiSoft** [comment]
@Remasuri This is now implemented in version `1.16.9` (beta branch). 

See documentation:
- Get model physics settings: `GetCurrentModelPhysicsRequest`
- Temporarily override model physics settings: `SetCurrentModelPhysicsRequest`

Please test and let me know if there are any issues. Wind direction isn't implemented, might add that in the future.
