### ISSUE TITLE
Feature Request: Request to see if expressions are set/unset

### ISSUE THREAD

**Issue by Bpendragon** [DenchiSoft/VTubeStudio#18]
The ability to see which expressions are set and unset would allow for potentially fluid transitions/swaps between expressions. 

## Proposal:

One function added to API `ExpressionStateRequest` (this could also potentially be rolled into the hotkey request since that will return only expressions that can be toggled via the API).

Potential implementation:

`REQUEST`

```json
{
	"apiName": "VTubeStudioPublicAPI",
	"apiVersion": "1.0",
	"requestID": "SomeID",
	"messageType": "ExpressionStateRequest",
	"data": {
		"expressionID": "Optional_ExpressionFileName",
	}
}
```

If an `ExpressionFileName` is provided the return Array will have a single item containing only that Expression.

It might also make sense to expose expressions via unique IDs. 

`RESPONSE`

```json
{
	"apiName": "VTubeStudioPublicAPI",
	"apiVersion": "1.0",
	"timestamp": 1625405710728,
	"requestID": "SomeID",
	"messageType": "ExpressionStateResponse",
	"data": {
		"modelLoaded": true,
		"modelName": "My Currently Loaded Model",
		"modelID": "UniqueIDOfModel",
		"expressionStates": [
			{
				"file": "myExpression_1.exp3.json",
                                "expressionSet": true
			},
			{
				"file": "myExpression_2.exp3.json",
                                "expressionSet": false
			}
		]
	}
}
```

## Use Case:

In my case my model (an MLP:FiM style unicorn wearing an umbreon kigurumi) has a base model with no mane:

![image](https://user-images.githubusercontent.com/5448822/144117354-ead10ab5-6ddf-43c5-861d-52ed03fd753f.png)

and two (relevant) available expressions:

* "Hood Down" which places a normal mane on the model: 
![image](https://user-images.githubusercontent.com/5448822/144117522-6e5974da-7b2c-4e85-8d58-543331e2e5eb.png)
* and "Hood Up" which puts the hood up: 
![image](https://user-images.githubusercontent.com/5448822/144117668-900d2ce6-8c18-4aba-a579-ee38d080e679.png)

To swap between the two I have to make sure to set/unset both or I get a weird chunk of man outside the hood: 
![image](https://user-images.githubusercontent.com/5448822/144117868-1a003e83-27ea-4260-9534-9c7921b15287.png)

Currently I am using Cazzar's plugin for the Stream Deck and running a multi-action to set/unset both simultaneously. In one direction it looks pretty ok, in the other it will always flash to the no mane at all look for a fraction of a second. However with the proposed change I (and others) could set and unset the expressions in the order that looks best on stream. 

Example of how that might work:

```
bool isHoodUp = <API Request Result>
if(isHoodUp) {
    <SendRequest ToggleHoodDown>
    <SendRequest ToggleHoodUp>
}  else {
    <SendRequest ToggleHoodUp>
    <SendRequest ToggleHoodDown>
}
```
(note how the order is swapped in each half of the if/else)

**Comment by DenchiSoft** [comment]
Thanks for the detailed proposal. I think being able to manually trigger expressions and read out expression states would definitely be useful. Will consider that for the next API update (probably the next update after the one coming up).

This is unrelated to the proposal, but as for your specific issue, you could probably solve that using some clever Live2D modeling as well.

**Comment by Bpendragon** [comment]
> This is unrelated to the proposal, but as for your specific issue, you could probably solve that using some clever Live2D modeling as well.

Yeah, I've been thinking about how I might do that, I don't know Live2d myself, but I've got some ideas (the artist I commissioned is otherwise quite busy). I've got a perfectly fine workaround for now. But having a programmatic way to guarantee it would be pretty nice.

**Comment by DenchiSoft** [comment]
This is now implemented in the new `ExpressionStateRequest` (see documentation). There is also the `ExpressionActivationRequest` to directly activate and deactivate expressions independently of hotkeys.

Both are available on the beta branch (version 1.15.10 or newer). Could you please give it a try and let me know if they work as expected?

Info on how to get on the beta branch can be found in the [VTube Studio Discord](https://discord.gg/VTubeStudio) in the **#beta_info** channel.

**Comment by Bpendragon** [comment]
I'll take a look in the next couple days. Life got a little busy, but I'll definitely give it a go when I can.

**Comment by DenchiSoft** [comment]
All good. I'll just close this eventually once someone has tested it. If you do test it, feel free to post here (if it's still open) or in the VTS Discord.
