### ISSUE TITLE
Question: How to further scale Live2D model

### ISSUE THREAD

**Issue by Mercynary-Z** [DenchiSoft/VTubeStudio#29]
My Live2D model is too large and exceeds the screen even I scroll mouse wheel to the minimum scale. I tried to edit the "Scale" key in vtube.json directly and it seems not work, the minimum valid scale value is 0.05.
![Screenshot 2022-04-14 172215](https://user-images.githubusercontent.com/26087322/163357267-fe100ade-3061-4f51-9f20-78f747dcfccf.png)

![Screenshot 2022-04-14 172842](https://user-images.githubusercontent.com/26087322/163357663-61d4a3a3-01ce-4077-beb8-b80f4fa967c3.png)

Help needed, Thanks!

**Comment by shell1986** [comment]
How did you solve this problem?
