### ISSUE TITLE
custom item that is a html page

### ISSUE THREAD

**Issue by kireita** [DenchiSoft/VTubeStudio#33]
Hey there.

I was checking out how items work and at the moment it does not support anything other than images.

Will it be possible in the future to make something similair like a browser window as an item (something like browsersource in OBS)?

i made a program in javascript that makes speechbubbles and does TTS and fits perfectly on a Vtuber but it the position is static at the moment and i would like to attach it to the face of the model. so i thaught about making it work like an item, would this be possible in the future?
 
here is an example of my program
![program](https://i.imgur.com/yv0Uc78.png)

if this is currently not possible. Would it then be possible to develop a plugin in vtube studio to integrate this:
[Ultralight](https://ultralig.ht/), this makes it possible to make UI elements with HTML,CSS and javascript and is compatible with unity.
i just dont know if your software allows to create plugins IN vroid studio itself

**Comment by DenchiSoft** [comment]
Interesting. I'll investigate this. The idea of rendering web-content directly into VTS certainly sounds interesting, especially for interactivity, but opening that up to plugins also brings with it a whole bunch of potential security issues.

**Comment by kireita** [comment]
I would gladly help, but again i dont know if it is possible to develop plugins IN Vtube studio it would work like a addon or DLC or extension.

otherwise i will wait for it and use the API for now (Using the basic model position), i tried using custom parameters but they are very limited as well :(

thanks for listening :)

you can close the issue if you want

**Comment by kireita** [comment]
I solved my issue for now (you can see the result in discord if you want), i will keep an eye on the updates to see if you guys expand the api to expose a body part's position or integrate web elements to view items.

i will close the issue for now, thanks!
