### ISSUE TITLE
BUG - Background Color Select Panel - Blue Slider doesn't work

### ISSUE THREAD

**Issue by TheArtGun** [DenchiSoft/VTubeStudio#36]
[https://gyazo.com/0f043fe4c40e0bb694d1267e7f2e1fad](url)

Video above- noticed this a while ago (I think in the last update) but thought it might just be my copy for some reason but found it's still there after steam updated it still, so I'm putting it here!

**Comment by DenchiSoft** [comment]
Fixed a while ago, see https://trello.com/c/XVwqhz0v
Will be included in the next update.
