### ISSUE TITLE
Request: Cyclic and Temporal Parameters

### ISSUE THREAD

**Issue by BoThompson** [DenchiSoft/VTubeStudio#40]
It would be incredibly useful to be able to create input parameters that automatically increment over time with the possible ability to set a cycle length before they automatically reset. I imagine this could be done via a plugin but it seems like the kind of thing that opens fundamental possibilities like looping effects and time-based events without needing any external programming.

I know at first glance for some this will sound identical to auto breath, but because breath oscillates as opposed to overflowing and resetting, anything dependent on it has to be designed around having the motion reversed, where this wouldn't.

**Comment by DenchiSoft** [comment]
Something like that has been requested before. You can track it here: https://trello.com/c/2pxzM80w

Other than that, you could definitely make a plugin that does this.
