### ISSUE TITLE
API Response is blocking

### ISSUE THREAD

**Issue by cnSchwarzer** [DenchiSoft/VTubeStudio#43]
I am developing a plugin that make websocket connection from mobile device via 5GHz WiFi, however the signal is not so strong, that makes the connection not so reliable.

I mainly use `InjectParameterData` at 60FPS, and the VTS program just stuck there. I use dnSpy to decompile the assembly (forgive me for reversing your program but it is urgent) because in Update function it use a while to dequeue every requests
![image](https://user-images.githubusercontent.com/29846655/181686231-32862379-563c-487a-9439-7b55094e8427.png)
It seems the processing cost is larger than 16ms, that cannot process in a frame, which makes it stuck. However a localhost plugin like VBridger doesn't stuck, that makes me think it is related to response codes.

And in the executor of `InjectParameterData`, it uses this to send response.
```csharp
VTubeStudioAPI.sendToSession<InjectParameterDataResponse>(basicResponse);
```

Even the API says it is async, it is not.
![image](https://user-images.githubusercontent.com/29846655/181686190-d40fff9b-b135-4fd4-af52-f85f0c72d8c1.png)

And after I wrap this code in an async block and recompile the assembly
![image](https://user-images.githubusercontent.com/29846655/181686349-1ef60642-c545-4ff1-8d2c-ed977d744614.png)
![image](https://user-images.githubusercontent.com/29846655/181686320-1e7d9d53-387e-4d1c-9893-38e34251a481.png)

The program never stuck again, and my plugin works like a charm.
Please consider move all response code in real `async void` functions, and not rely on the buggy implementation the `websocket-sharp` provide.

**Comment by DenchiSoft** [comment]
This is now implemented starting version 1.21.11
