### ISSUE TITLE
Checking the (?) on "Load this Model as a Live2D Item" config "Use Normal Hotkey Triggers" leads to a dead end

### ISSUE THREAD

**Issue by TheArtGun** [DenchiSoft/VTubeStudio#44]
![image](https://user-images.githubusercontent.com/46326918/187018137-e9ddda1d-9fab-4c22-b634-da79b7ad852d.png)

There seems to be no way to escape this screen once it opens!
Specifically it's from clicking this (?) 
![image](https://user-images.githubusercontent.com/46326918/187018204-a5e65bce-47e2-47b7-ba82-aed0284e3585.png)

**Comment by DenchiSoft** [comment]
Thanks for reporting, will be fixed in the next update.
