### ISSUE TITLE
DISPARITY: modelName value is different between Request and Event API.

### ISSUE THREAD

**Issue by FomTarro** [DenchiSoft/VTubeStudio#47]
The `modelName` value returned via the ModelLoadEvent subscription API and the `modelName` value returned via the GetCurrentModel request API are different, even though the payload is the same structure, one would think they behave the same.

For example, when this one loads, the event API gives me `modelName: 'skeletom_real'` while the request API gives me `modelName: 'skeletom'`. Akari, for example, comes back as `akari` over request and `Akari` over event.

![image](https://user-images.githubusercontent.com/10201349/199074513-fc4caac4-34ff-4d6c-9a56-8b6f87da5eb3.png)

**Comment by DenchiSoft** [comment]
Thanks for reporting, fixed. Will be included in the next update.

The `modelName` in the event now behaves like the `modelName` in the regular `CurrentModelRequest`.
