### ISSUE TITLE
Tobii Eyetracker 5 + Webcam & Glasses

### ISSUE THREAD

**Issue by imagoth2004** [DenchiSoft/VTubeStudio#56]
I was told to create a support ticket for this: I'm mainly aiming for a change in the program to allow the Tobii tracker to be used for eye blink instead of the webcam. Main issue being that light reflection from the glasses will cause the webcam video input to fluctuate.

[Link to video to show what I mean.](https://www.youtube.com/watch?v=thv1MKjQ0_E)

**Comment by DenchiSoft** [comment]
This repository is specifically for bug reports regarding the VTube Studio API. For general questions and feature requests for the main app, please post in the VTube Studio Discord: https://discord.gg/VTubeStudio

There are enhancements planned for how VTube Studio uses Tobii tracking for late 2023. Changes to how blinking is treated could certainly be part of that.
