### ISSUE TITLE
BUG: Idle animation wrongfully overwritten by face tracking when camera is OFF

### ISSUE THREAD

**Issue by yutamago** [DenchiSoft/VTubeStudio#67]
When you launch VTS, the idle animation is playing but all the trackable inputs are not moving.

When you turn on the camera and lose tracking, the idle animation will play properly.

Looking at the documentation, the idle animation should only be overwritten, when there's actual tracking happening, but there's not:
https://github.com/DenchiSoft/VTubeStudio/wiki/Interaction-between-Animations%2C-Tracking%2C-Physics%2C-etc.
![image](https://github.com/DenchiSoft/VTubeStudio/assets/12561505/29e6e630-b0b0-456a-a480-3b2a52235fb0)

The same issue is happening when you turn the camera off mid-tracking. The idle animation will still be overwritten by the non-existing tracking.

There's a workaround (although very inconvenient):
- Turn on the camera and wait until it tracks your face
- lose tracking (by covering the camera or moving out of frame)
- turn off the camera

**Comment by DenchiSoft** [comment]
Thanks for reporting. This was fixed a while ago and will be included in the next update.

More info: https://trello.com/c/DXRTPq1Q
