### ISSUE TITLE
Outdated "running on linux" wiki

### ISSUE THREAD

**Issue by YouHaveTrouble** [DenchiSoft/VTubeStudio#68]
[Wiki page in question](https://github.com/DenchiSoft/VTubeStudio/wiki/Running-VTS-on-Linux). Page specifies that numpy 1.21.6 is needed, but after a failed attempt to run OpenSeeFace on that version I updated to numpy 1.26.1 and everything seems to be in working order.

**Comment by DenchiSoft** [comment]
Fixed, thanks.
