### ISSUE TITLE
Please separate `$` from commands in the wiki

### ISSUE THREAD

**Issue by 5ucur** [DenchiSoft/VTubeStudio#69]
In the [Linux guide](../wiki/Running-VTS-on-Linux) on the wiki, the commands are like so:

`$sudo pacman -Sy python39`

This makes it less easy to not include the `$` character when copying commands. Instead I propose that the commands be separated from the `$` character by a space, like so:

`$ sudo pacman -Sy python39`

This is standard for any guides for Linux commands, to separate the prompt from the command, with `$` being regular user, and `#` being root user. The prompt itself in the terminal is separated normally from the command, too.

Also please, never use `pacman -Sy`. Either do `pacman -Syu` for a full upgrade, or do `pacman -S` to download from the mirrors that correspond to the current state of the system.

**Comment by DenchiSoft** [comment]
Done. Thanks for letting me know!
