### ISSUE TITLE
ws接口可以控制参数的自动呼吸的开关吗？

### ISSUE THREAD

**Issue by worm128** [DenchiSoft/VTubeStudio#73]
ws接口可以控制参数的自动呼吸的开关吗？
![图片](https://github.com/DenchiSoft/VTubeStudio/assets/29749635/b5cf8452-d2fc-4f7d-b528-06180e91e923)

**Comment by DenchiSoft** [comment]
Currently you cannot control auto-breath/blink settings via the API. But since you have full control over the injected parameter values, you can just do your own auto-breathing.
