### ISSUE TITLE
Add connect Android via USB Debugging mode

### ISSUE THREAD

**Issue by GuraNotFound** [DenchiSoft/VTubeStudio#74]
As the title says, I want the "wired connection to Android phone via USB Debugging" functionality.

Partly because I find Android users quite annoyed every time the Access Point malfunctions, but if they want to use a wire, they have to buy an iPhone!

Partly because I prefer to use Android over the iPhone because it is open source and can install my own custom Android operating system that I like!

**Comment by DenchiSoft** [comment]
I've been looking at this before but I couldn't get reliable USB serial communication working on Android. Might look into it again in the future, but right now I don't have any working library I could use for this.
