### ISSUE TITLE
Does the API work with the mobile VTS apps?

### ISSUE THREAD

**Issue by ashmanix** [DenchiSoft/VTubeStudio#76]
I want to get tracking data from the vTube Studio app on my phone to send to an app I have made to run on the desktop. Does the API listed here apply to the mobile apps at all?

I've noticed that there are options to stream to PC via WiFi (I assume this is to vTube Studio on PC) and there is a third party integration switch for use with VSeeFace. Is there any API for these that can be used by other apps on the same network?

**Comment by DenchiSoft** [comment]
There's a way for 3rd party apps to request tracking data (raw blendshapes, rotation, position) from the iOS app but I haven't written any documentation for that yet. Currently it's just used by VSeeFace and VBridger I think.

Not sure why I never documented it. I'll get on that for the next release.

**Comment by ashmanix** [comment]
Awesome! Thanks!

**Comment by DenchiSoft** [comment]
The documentation and an example app is now available here: https://github.com/DenchiSoft/VTubeStudioBlendshapeUDPReceiverTest

**Comment by ashmanix** [comment]
Thanks!!!
