### ISSUE TITLE
No Error Response to HotkeysInCurrentModelRequest when not providing modelID in data

### ISSUE THREAD

**Issue by Blazified** [DenchiSoft/VTubeStudio#78]
When sending a "HotkeysInCurrentModelRequest" without "modelID" but including "live2DItemFileName" in the data, no response is given.

Like this: 
``` json
"data": {
    "live2DItemFileName": "FILENAME"
}
```
With no error i couldn't tell what when wrong since in the documentation...
 
> If both "modelID" and "live2DItemFileName" are provided, only "modelID" is used and the other field will be ignored.

This is false as my work around to the issue is to provide no "modelID" like this:
``` json
"data": {
    "modelID": "",
    "live2DItemFileName": "FILENAME"
}
```

Please update documentation and fix no error response when only providing "live2DItemFileName" :)

**Comment by DenchiSoft** [comment]
Thanks for reporting. The fix for this will be included in the next update.

To track the fix: https://trello.com/c/Hh3KUOFH
