### ISSUE TITLE
2.4GHz WiFi pop-up button redirects to wrong link?

### ISSUE THREAD

**Issue by ebikatsudon** [DenchiSoft/VTubeStudio#84]
Hello, I noticed when starting up VTube Studio, clicking the "More Info" button on the pop-up message about using 2.4GHz WiFi redirects to the Live2D Free Material License Agreement (https://www.live2d.jp/en/terms/live2d-free-material-license-agreement/). Is this the intended resource? There's nothing about WiFi connection on that page.

![pop_up](https://github.com/user-attachments/assets/49c820ca-9e52-420c-ae41-9ca9055dc5cb)

**Comment by DenchiSoft** [comment]
Thanks a lot for reporting! That link is indeed not supposed to be there. It will be removed with the next update.
