### ISSUE TITLE
Request to Change Default Port from 25565 to Avoid Minecraft Conflict

### ISSUE THREAD

**Issue by jaku** [DenchiSoft/VTubeStudio#88]
I initially made this request on Discord but realized GitHub might be a better spot for this.

I understand that VTube Studio has been using port 25565 as its default for a while. However, Minecraft servers have used this port for over 10 years, which creates conflicts for creators who run temporary Minecraft servers on their streaming PCs—a common practice.

The specific issue: Creators often run Minecraft servers using the default port (25565) without issues during testing. However, when they go live and use VTS, they typically start VTS first and then try to launch their Minecraft server. Because VTS is already using the port, Minecraft cannot run the server properly, and this leads to disruptions during live streams. 

To mitigate this issue, I suggest changing the default port for new VTS installs/setups to 25566. For older installs, maybe the default port could be updated as long as the user hasn’t manually set it to 25565. 

If they opened it the other way around, VTS would typically find a new port automatically which makes me believe this request shouldn't be difficult to implement since the software already handles different ports fairly well. Additionally, while it’s possible for users to manually change the port for either Minecraft or VTS, the issue is that it requires users to understand the conflict is happening in the first place, which can be stressful for them to figure out while streaming live.

Thanks.

**Comment by DenchiSoft** [comment]
I'll consider it. Not sure why I chose 25565 to begin with. For now, if you change the port manually, VTS should remember the new port for subsequent startups.
