### ISSUE TITLE
api refuses connection

### ISSUE THREAD

**Issue by nekohacker591** [DenchiSoft/VTubeStudio#89]
Received message: {"apiName":"VTubeStudioPublicAPI","apiVersion":"1.0","timestamp":1728144856993,"messageType":"APIError","requestID":"2","data":{"errorID":8,"message":"Current session is not authenticated. The only requests you can send without authenticating are: [APIStateRequest, AuthenticationTokenRequest, AuthenticationRequest]"}}

**Comment by DenchiSoft** [comment]
The error message should be pretty clear. You tried to send a request that requires authentication but your session wasn't authenticated yet.

You must first request a token using the `AuthenticationTokenRequest` and then authenticate your session using the `AuthenticationRequest`. After that, you can use all the other requests.

See also: https://github.com/DenchiSoft/VTubeStudio?tab=readme-ov-file#authentication
