### ISSUE TITLE
Bug/Enhancement: upgrade/refactor NDI output for better NDI HX compatibility

### ISSUE THREAD

**Issue by oldking139** [DenchiSoft/VTubeStudio#90]
![image](https://github.com/user-attachments/assets/490a59d0-142b-47aa-9866-fc157b01885e)

We met some weird problem on NDI Signals from VTS, and how we use VTS is quite rare compare to majority of users, so let me explain briefly.

We are a tech/supporting/consulting company focus on the online/offline/hybrid Vtuber events in China, and this is what we investigate and decide on most of offline events solutions:
- multiple PCs running VTS and using NDI output (sometimes more than 8) for livers
- _Since NDI signal will use multiple bandwidth if we have multiple receiver (e.g. 1 receiver using 100Mbps on uploading, 3 receiver using 300), for reducing the network pressure on LAN (and PC which runs VTS), we decide using a NDI route/switch for better produciton_
- using a [NDI route/switch](https://www.kiloview.com/en/ndi/ndi-core/) to receive NDI signals from VTS PC, and distribute to our production workstation (PCs and video switchers)
![image](https://github.com/user-attachments/assets/949a0787-4305-494f-babf-32ee47d40da5)

So far, everything is fine as we using the original NDI signals from VTS Directly.

---

However, original NDI signals still consuming quite a lot on bandwidth, typically around 90~160Mbps, which just few signals can run out a 1G ethernet connection.
NDI tools officially support an app that can transcod NDI signals with custom bandwidth setting that we can configure to what we need, called [NDI Bridge](https://ndi.video/tools/ndi-bridge/). And the Encoded NDI signals called "NDI HX". Now we met problem.
- we send the transcoded VTS NDI HX signals to NDI-CORE, and when we try to route out the signals, we see the errors shows on the top . "Video decoder not found"
- **after we check with our software with NDI output, we confirm that only VTS has this problem. we test ["Test patterns" from official NDI tools](https://ndi.video/tools/ndi-test-patterns/), [obs-ndi](https://github.com/DistroAV/DistroAV) on OBS as a OBS output, and also [Shoost from Muro](https://www.patreon.com/posts/62585593). All of these tools can be transcoded to NDI HX signals and send out from NDI-CORE.**

![image](https://github.com/user-attachments/assets/163224e1-0d63-418c-8201-21be61b0ddb7)

I am not sure how NDI was implement into VTS (write from scratch or using some SDK), and how long did this feature not upgrade after last time, so after we troubleshooting with support team from NDI-CORE, we need some more info for this problem:
- _**Any version information you can give us, e.g. the NDI HX version, NDI version, or SDK version if using SDK.**_

![image](https://github.com/user-attachments/assets/0bedd78a-4fc9-4dc1-be09-c0c1da7bcada)

---

More information if needed:
[NDI-CORE from Kiloview](https://www.kiloview.com/en/ndi/ndi-core/)
[NDI TOOLS](https://ndi.video/tools/)
[NDI HX](https://vdo360.com/question/what-is-the-difference-between-ndi-and-ndi-hx/)

I know VTS will be totally fine without this fixing (or upgrading), as rightnow it "just works" on everyone's machine. But if it fixed, it will be more suitable for Vtube events that runs on traditional broadcasting workflow.

**Comment by oldking139** [comment]
By the way, it would be better if the NDI name can change from "Live2D Camera NDI5" to just "Vtube studio NDI", especially when you have tons of NDI sources on list.

**Comment by DenchiSoft** [comment]
VTube Studio uses KlakNDI to send NDI streams: https://github.com/keijiro/KlakNDI
I am not using the most recent version of this plugin. The version I use is from just after NDI 5 support was added.

As for thee NDI version, I'll have to check, but I believe the version of KlakNDI VTubeStudio uses has the NDI SDK 5.5.2.

I've tried to replicate this on my side and with the newest NDI Tools (6.0.1.0), everything seems to work fine. The transcoded NDI HX output showed up fine in the Monitor (and also OBS).

The error you're seeing seems to imply that it can't find a decoder for the video stream. The stream is encoded with H.264, can you check if a decoder for that is installed? Clicking the "Check Compatibility" button in the Bridge encoder settings should show you what's installed.

As for the source name, would it help you if that was made configurable?

![ndi_test](https://github.com/user-attachments/assets/254eb871-7da1-4a66-b7c4-d1097093fdda)

**Comment by DenchiSoft** [comment]
Also, I realize I missed a step since I'm not checking the NDI Core output but the output directly from the NDI Bridge.

But the error screen you're seeing seems to come from the NDI Bridge and not NDI Core if I'm not mistaken? Can you check the NDI HX output coming from the NDI Bridge? Are you using the most recent version of NDI Tools (6.0.1.0)?

**Comment by oldking139** [comment]
You are totally right! The NDI HX through local is working correctly with no issues, let me clarify where the problem is.

Only the HX through NDI-CORE have this problem, that's why we try to figure out whether it is a VTS issue or the NDI-CORE issue. 
![image](https://github.com/user-attachments/assets/fab6e386-dd2d-45e8-b625-2b5867bc0e4b)


By the way, both VTS PC and production station have all codec installed with valid GPU and GPU driver for hardware acc.
![image](https://github.com/user-attachments/assets/b3ab975c-956a-4227-8edd-b857c10600c6)

**Comment by oldking139** [comment]
> Also, I realize I missed a step since I'm not checking the NDI Core output but the output directly from the NDI Bridge.
> 
> But the error screen you're seeing seems to come from the NDI Bridge and not NDI Core if I'm not mistaken? Can you check the NDI HX output coming from the NDI Bridge? Are you using the most recent version of NDI Tools (6.0.1.0)?

I confirm both VTS PC and production station runs NDI Tools 6.0.1.0

**Comment by DenchiSoft** [comment]
Maybe it's caused by an outdated NDI version in VTS then. Could you try updating the version manually just to see if that fixes it? If so, I can include the new version in the next VTS update.

Download this: https://github.com/keijiro/KlakNDI/blob/f57f62331e84ef1fdc0a9dc0ecb9f91bb18d0d3b/jp.keijiro.klak.ndi/Plugin/Windows/Processing.NDI.Lib.x64.dll

And put it in `VTube Studio_Data\Plugins\x86_64`, replacing the `Processing.NDI.Lib.x64.dll` that's already there. That will update the NDI SDK to `6.0.1`.

Let me know if that fixes the issue.

**Comment by oldking139** [comment]
I have rename the old `dll` and put new one in path you specify.
unfortunately the Result is same.

**Comment by oldking139** [comment]
Probably make a minimal reproduction that only include KlakNDI with a loop video is a good choice to find out the issue.

**Comment by DenchiSoft** [comment]
Does deactivating the "NDI v5" toggle in VTS change anything? That will force it to use an older version of the library.

----

Do you know what NDI Core does internally? Does it modify/transcode the stream at all?
I think one possible issue could be that the NDI stream coming from VTS supports transparency. The other apps you listed probably do not output an alpha channel. Maybe this somehow breaks NDI Core?

Specifically, VTS outputs UYVA pixel format instead of UYVY, which would be used when transparency is disabled (hardcoded as enabled in VTS). The NDI HX transcoding done in the NDI bridge retains that transparency, but maybe the output pixel format with transparency in the transcoded stream is not supported by NDI Core (whatever that format may be, I am not sure how to check).

**Comment by oldking139** [comment]
> Does deactivating the "NDI v5" toggle in VTS change anything? That will force it to use an older version of the library.

Unfortunately no.

> Do you know what NDI Core does internally? Does it modify/transcode the stream at all?

Kiloview said NDI-CORE is just a switcher, really similar to traditional SDI video matrix/switcher but just runs on IP with NDI. That means, no transcode on signals. I will double check with them.

> I think one possible issue could be that the NDI stream coming from VTS supports transparency. The other apps you listed probably do not output an alpha channel. Maybe this somehow breaks NDI Core?

Shoost made by Muro also have transparent NDI output. The result after testing is quite interesting.
| / | Shoost NDI Direct to NDI-CORE | Shoost NDI HX to NDI-CORE |
| :-----: | :------: | :-----: |
| filled background  |  ✔receiver no issue   | ✔receiver no issue   |
| transparent background |  ✔receiver no issue   | ❌Video decoder not found  |

So I also test VTS with transparent bg or not. More weird here.
During test I using the `6.0.1` of `Processing.NDI.Lib.x64.dll` and `NDI v5` switch **Enable**.
| / |  VTS NDI Direct to NDI-CORE | VTS NDI HX to NDI-CORE |
| :-----: | :------: | :-----: |
| filled background  |  ✔receiver no issue   | ❌Video decoder not found  |
| transparent background |  ✔receiver no issue   | ❌Video decoder not found  |

**Comment by oldking139** [comment]
The only same thing between Shoost and VTS probably just also build on Unity (As I do not have source code). The alpha output of NDI probably different from each other.

So far from Shoost test, we can see there is some problem in NDI-CORE as it cannot handle transparent signal with HX encoding.
But VTS  even cannot runs on fill bg and HX and that's a bit of a surprise to me.

PS: all signals (filled bg and transparent) work fine on local without going into NDI-CORE.

**Comment by DenchiSoft** [comment]
Interesting. Then transparency is probably what causes the issue. 

Whatever transparent NDI HX format is output by the NDI Bridge causes the NDI Core output to become invalid. I would assume that Shoost switches to the non-transparent pixel format when the background is filled.

> But VTS even cannot runs on fill bg and HX and that's a bit of a surprise to me.

VTS does not do that and always forces the transparent format, so using a filled/transparent background would not make a difference. The alpha channel is always sent.

But if NDI Core is really just a switcher, that's really strange. The stream going into it and coming out of it should be identical.

**Comment by oldking139** [comment]
Really thanks for you spending time tracking this strange issue!
I will contact Kiloview for more detail about signals with alpha channel.

**Comment by DenchiSoft** [comment]
No problem :)
Let me know when they get back to you. Maybe they could test on their side what happens when they receive a HX stream from the Bridge with transparency and if that is handled correctly.

**Comment by oldking139** [comment]
As we took tests with Kiloview support team, we find out this is an issue in NDI Bridge. Teams from NDI Tools said they will fix this in first  half of 2025, so for now we have not much things can do.
Thanks again for tracking this issue!
