### ISSUE TITLE
Steam blocked on my device

### ISSUE THREAD

**Issue by Strolled257** [DenchiSoft/VTubeStudio#94]
I want to vtube and i need vtube studio to do that. However due to (overbearing parents that dont understand that steam is an app store and not a social media) Steam is blocked on my device and im wondering if anyone has a download to provide so I can have vtube studio without steam(also discord is blocked too) Please help me also im seven teeth(i have to say it like this or ill get flagged) Please help me(also if the live2d people are reading this PLEASE MAKE A DOWNLOAD OUTSIDE OF STEAM, VROID HAS ONE SO PLEASE MAKE ONE, NOT ALL OF US HAVE ACCESS TO STEAM)

**Comment by Strolled257** [comment]
Edit: Itch.io is blocked too so if you have a direct file to provide that would be great qwq

**Comment by Strolled257** [comment]
Also if it's steam only due to brand deals and stuff, please reccomend alternatives(preferably free) that dont force you to use steam

**Comment by DenchiSoft** [comment]
Steam is required for updates and certain functionality like the workshop and multiplayer. VTube Studio will not be officially distributed outside of Steam for that reason. However, you only need Steam to download/update the app, so you could get a friend to download it and send it to you and then start it without Steam like this:

https://github.com/DenchiSoft/VTubeStudio/wiki/Starting-without-Steam
